### ISSUE TITLE
Hello,  Shopify latest version

### ISSUE THREAD

**Issue by dembee111** [gatsbyjs/gatsby-starter-shopify#43]
Sorry, How to get Shopify latest version api 2021-07

![Screen Shot 2021-08-16 at 11 23 08](https://user-images.githubusercontent.com/25500741/129507586-b0cf9e87-3ed5-4018-8f6e-14859a7e0145.png)

**Comment by LekoArts** [comment]
Update to the lastest version of the source plugin: https://www.gatsbyjs.com/docs/reference/release-notes/v3.12#improvements-to-gatsby-source-shopify
