### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by gcosgreave** [gatsbyjs/gatsby-starter-shopify#70]
I have just checked the project out added the store url and password everything is pulling through as expected but on reload I am getting the following runtime error: 

<img width="932" alt="image" src="https://user-images.githubusercontent.com/3886015/181576213-4ba7f293-6ac1-4acc-852a-2858beba7152.png">

Its also doing the same for the /search page and not returning any projects but is on the other pages. 

Any ideas?

**Comment by gcosgreave** [comment]
The issue here was how the custom app was set up. Now working as expected

**Comment by kishankapadia** [comment]
@gcosgreave How did you solve this error? Which custom app are you talking about?
